# Generated by Django 3.1.7 on 2021-03-13 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0007_auto_20210224_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.PositiveSmallIntegerField(choices=[(0, 'Заявка'), (1, 'Письмо'), (2, 'Сайт'), (3, 'Инициатива компании')], default=0, verbose_name='канал обращения')),
                ('description', tinymce.models.HTMLField(verbose_name='описание')),
                ('evaluation', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0, verbose_name='оценка')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='дата создания записи')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='дата изменения записи')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='компания')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='менеджер')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='проект')),
            ],
            options={
                'verbose_name': 'взаимодействие',
                'verbose_name_plural': 'взаимодействия',
            },
        ),
    ]
