# Generated by Django 3.1.7 on 2021-03-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=20, unique=True, verbose_name='слово')),
                ('slug', models.SlugField(max_length=20, verbose_name='слаг')),
            ],
            options={
                'verbose_name': 'ключевое слово',
                'verbose_name_plural': 'ключевые слова',
            },
        ),
        migrations.AddField(
            model_name='interaction',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='interactions.Keyword', verbose_name='ключевые слова'),
        ),
    ]
