# Generated by Django 3.1.7 on 2021-02-21 12:08

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='описание'),
        ),
    ]
