# Generated by Django 3.1.7 on 2021-02-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_auto_20210224_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='emails',
            field=models.ManyToManyField(blank=True, to='clients.Email', verbose_name='адреса электронной почты'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phones',
            field=models.ManyToManyField(blank=True, to='clients.Phone', verbose_name='телефоны'),
        ),
    ]
