# Generated by Django 3.1.7 on 2021-02-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_auto_20210221_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='emails',
            field=models.ManyToManyField(to='companies.Email', verbose_name='адреса электронной почты'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phones',
            field=models.ManyToManyField(to='companies.Phone', verbose_name='телефоны'),
        ),
    ]
